export const DEFAULT_RPC_URL = process.env.SOLANA_RPC_URL || "https://api.mainnet-beta.solana.com";
export const TOOL_VERSION = "0.1.0";
export const SCHEMA_VERSION = "0.1";

export const PROGRAMS = Object.freeze({
  SYSTEM: "11111111111111111111111111111111",
  TOKEN: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TOKEN_2022: "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
  ASSOCIATED_TOKEN: "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
  COMPUTE_BUDGET: "ComputeBudget111111111111111111111111111111",
  ADDRESS_LOOKUP_TABLE: "AddressLookupTab1e1111111111111111111111111",
  BPF_LOADER: "BPFLoader2111111111111111111111111111111111",
  BPF_UPGRADEABLE_LOADER: "BPFLoaderUpgradeab1e11111111111111111111111",
  LOADER_V4: "LoaderV411111111111111111111111111111111111",
  WRAPPED_SOL_MINT: "So11111111111111111111111111111111111111112",
});

export const TRANSACTION_CLASSES = Object.freeze({
  SYSTEM_TRANSFER: "SYSTEM_TRANSFER",
  CLASSIC_SPL_TRANSFER: "CLASSIC_SPL_TRANSFER",
  SUPPORTED_DETERMINISTIC_FAILURE: "SUPPORTED_DETERMINISTIC_FAILURE",
  UNSUPPORTED: "UNSUPPORTED_TRANSACTION_CLASS",
});

export const ELIGIBILITY = Object.freeze({ SUPPORTED: "SUPPORTED", UNSUPPORTED: "UNSUPPORTED" });

export const PROVENANCE = Object.freeze({
  PROVEN: "PROVEN",
  INFERRED: "INFERRED",
  CURRENT_ONLY: "CURRENT_ONLY",
  UNKNOWN: "UNKNOWN",
});

export const REASON_CODES = Object.freeze({
  ALT_HISTORICAL_STATE: "UNSUPPORTED_ALT_HISTORICAL_STATE",
  PROGRAM_PROVENANCE: "UNSUPPORTED_PROGRAM_PROVENANCE",
  ACCOUNT_PRESTATE: "UNSUPPORTED_ACCOUNT_PRESTATE",
  UPGRADEABLE_PROGRAM_VERSION: "UNSUPPORTED_UPGRADEABLE_PROGRAM_VERSION",
  ORACLE_DEPENDENCY: "UNSUPPORTED_ORACLE_DEPENDENCY",
  TEMPORAL_DEPENDENCY: "UNSUPPORTED_TEMPORAL_DEPENDENCY",
  RUNTIME_MISMATCH: "UNSUPPORTED_RUNTIME_MISMATCH",
  TRANSACTION_CLASS: "UNSUPPORTED_TRANSACTION_CLASS",
  CORRUPTED_BUNDLE: "CORRUPTED_BUNDLE",
  INVALID_SCHEMA_VERSION: "INVALID_SCHEMA_VERSION",
});

export const REASON_MESSAGES = Object.freeze({
  [REASON_CODES.ALT_HISTORICAL_STATE]: "historical Address Lookup Table state is unavailable",
  [REASON_CODES.PROGRAM_PROVENANCE]: "executed program bytes are not proven for the original slot",
  [REASON_CODES.ACCOUNT_PRESTATE]: "one or more relevant accounts lack defensible pre-state",
  [REASON_CODES.UPGRADEABLE_PROGRAM_VERSION]: "upgradeable program version at the original slot is not proven",
  [REASON_CODES.ORACLE_DEPENDENCY]: "oracle input cannot be reconstructed with historical provenance",
  [REASON_CODES.TEMPORAL_DEPENDENCY]: "slot, clock, epoch, rent, or recent-state dependency is not reconstructed",
  [REASON_CODES.RUNTIME_MISMATCH]: "bundle runtime requirements do not match this Solana Repro runtime",
  [REASON_CODES.TRANSACTION_CLASS]: "transaction is outside the explicit MVP allowlist",
  [REASON_CODES.CORRUPTED_BUNDLE]: "bundle integrity validation failed",
  [REASON_CODES.INVALID_SCHEMA_VERSION]: "bundle schema version is unsupported",
});

export const FIDELITY = Object.freeze({
  EXACT: "EXACT",
  HIGH_FIDELITY: "HIGH_FIDELITY",
  PARTIAL: "PARTIAL",
  FAILED: "FAILED",
  UNSUPPORTED: "UNSUPPORTED",
});
